### ISSUE TITLE
Datenbank-Schema konzipieren

### ISSUE THREAD

**Issue by Lachstec** [Lachstec/mc-hosting#22]
Einmal ein ER-Diagramm zusammenschußtern mit den Grundlegenden Entities, die für die Anwendung gebraucht werden

## TODOs
- [ ] Wie mit einer DB verbinden?
- [ ] Datenbank-Schema wie managen?
- [ ] Welche Typen werden gebraucht?
